---
- hosts: dbservers
  gather_facts: False
  roles:
    - common
    - postgresql
    - db

- hosts: appservers
  serial: 1
  roles:
    - common
    - java
    - users
    - app

- hosts: proxies
  gather_facts: False
  roles:
    - common

