---
- name: Copy config.properties
  template:
    src=config.properties.j2
    dest=/home/{{ user }}/config.properties
    owner={{ user }}
    group={{ group }}
    mode=0640
  tags:
    - deploy

#- name: Download jar
#  get_url:
#    url="http://morisbak.net/files/devops.jar"
#    dest="/home/{{ user }}/devops_{{ deploy_stamp }}.jar"
#    owner={{ user }}
#    group={{ group }}
#    mode=0644
#  tags:
#    - deploy


- name: Copy app jar
  copy:
    src=../../../helloworld-java-app/target/helloworld-java-app-1.0-SNAPSHOT-jar-with-dependencies.jar
    dest=/home/{{ user }}/devops_{{ deploy_stamp }}.jar
    owner={{ user }}
    group={{ group }}
    mode=0644
  tags:
    - deploy

- name: Link to previous app releases
  shell: "ln -nsf $( readlink /home/{{ user }}/current ) /home/{{ user }}/previous"
  tags:
    - deploy

- name: Link to current app releases
  file:
    dest="/home/{{ user }}/current"
    src="/home/{{ user }}/devops_{{ deploy_stamp }}.jar"
    owner={{ user }}
    group={{ group }}
    state=link
    force=yes
  tags:
    - deploy

- name: Copy init script to server
  copy:
    src=init.sh
    dest=/etc/init.d/devops
    owner={{ user }}
    group={{ group }}
    mode=0755
  tags:
    - deploy

- name: Enable and restart app service
  service:
    name=devops
    enabled=yes
    state=restarted
    sleep=3
  remote_user: devops
  sudo: False
  tags:
    - deploy

- name: Wait until app is available
  local_action: wait_for port={{ http_port }} host={{ inventory_hostname }} delay=5
  sudo: False
  tags:
    - deploy
    - status

- name: Remove old deploys (keeping the two latest)
  shell: "ls -tr /home/{{ user }}/devops_*.jar | head -n -2 | xargs rm -Rf"
  tags:
    - deploy

