---
- name: Create group
  group: name=<insert group variable here> state=present
  tags:
    - users

- name: Create user
  user:
    name=<insert user variable here>
    comment="<insert user_name variable here>"
    group=<insert group variable here>
    createhome=yes
    home=/home/<insert user variable here>
    shell=/bin/bash
    state=present
  tags:
    - users

- name: Ensure ssh directory exists for user
  file:
    dest=/home/<insert user variable here>/.ssh
    owner=<insert user variable here>
    group=<insert group variable here>
    state=directory
    mode=0700
  tags:
    - users

- name: Ensure public key is in authorized_keys
  lineinfile:
    dest=/home/<insert user variable here>/.ssh/authorized_keys
    state=present
    line="{{ lookup('file','~/.ssh/id_rsa.pub') }}"
    insertafter=EOF
    create=yes
    owner=<insert user variable here>
    group=<insert group variable here>
    mode=600
    regexp=stein.inge.morisbak@BEKK.no$ # substitute with the end of your personal public key>
  tags:
    - users

