---
- name: Copy db migration script
  copy: src=migrate_db.sql dest=/tmp/migrate_db.sql
  become_user: postgres
  tags:
    - deploy

- name: Run db migration script
  command: psql -d {{ db.name }} -q -f /tmp/migrate_db.sql
  become_user: postgres
  tags:
    - deploy
